### ISSUE TITLE
Consider more tasks for a weekly cron

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-bot#117]
We currently have two cron jobs that close stale issues and pull requests, and I can think of some other things it might be nice to automate on a similar timescale in the core package specifically:

* Running the IERS update script (``update_builtin_iers``) (EDIT: https://github.com/astropy/astropy/blob/master/astropy/utils/iers/data/update_builtin_iers.sh)
* Updating the list of contributors in ``credits.rst`` (EDIT: see astropy/astropy-procedures#122 and https://github.com/sunpy/sunpy/blob/master/tools/generate_releaserst.xsh)

and potentially other actions. This could then result in a e.g. weekly or monthly PR by the bot to update the relevant files.

We could also consider some kind of automation for backports, and could leave a comment on PRs that can't be backported cleanly (or open an issue about it). Obviously this requires more thought, but just brain dumping for now.

If we can automate some of these things, it could mean less work at release time.

**Comment by pllim** [comment]
This looks like an "epic" (JIRA speak!) and will need to be broken down to smaller items that people can tackle. Or at least a concrete check list.

Like, the first 2 bullets can be turned into checkboxes, and then the "brain dumping" part can be a few more.

**Comment by pllim** [comment]
> We currently have two cron jobs that close stale issues and pull requests

By the way, are the cron job scripts even in this repo? I cannot find them.

**Comment by pllim** [comment]
For "Updating the list of contributors," does that cron job have `git` installed?

**Comment by bsipocz** [comment]
Imo updating the contributors from cron will generate more interrupts and actions for maintainers than doing it in one go before a release. Names are not easy, and many times are not automatable (see badly configured git, duplicate names, spelling variations, etc).

**Comment by pllim** [comment]
> Running the IERS update script

Here are the steps from `astropy` release procedures:

1. Use `git` to grab the latest `master` branch of `astropy`.
2. Change directory to `astropy/utils/iers/data`.
3. Execute `update_builtin_iers.sh`.
4. Open a PR if there is a difference (in `eopc04_IAU2000.62-now`?).

**Comment by pllim** [comment]
Re: Running the IERS update script

I have a proof-of-concept script using `batchpr` in [this gist](https://gist.github.com/pllim/9f0e121e1a13e13ac68705c619dd3fa1). Seems to work when there is a change (see astropy/astropy#10500).

TODO:

* Have to test to see if it will refrain itself from opening a dummy PR when there is no diff. 
* Have to think about what happens when there is a PR open by the cron job already, but we are not fast enough to merge it, and cron job kicks off again and opens a duplicate PR (assuming hardcoding branch name won't prevent the duplicate PR from being open in the first place, also see the next point).
* Also have to think about when cron job opens PR 1 with some changes, no one merges it, cron job runs again and this time finds those changes and also new changes, but the branch name is hardcoded into the script already. Will that causes PR 1 to update automatically? Or will the second run fails and we cannot get latest changes until PR 1 is merged?
* How often should this run?
* How do we update the `astropy` release procedure to reflect this?
