### ISSUE TITLE
TST: Add flake8 check for bot?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#44]
Or is this an overkill?

**Comment by bsipocz** [comment]
I think we could use pep8speak instead (works nicely for sunpy and astroquery) rather than start writing our own.

**Comment by pllim** [comment]
I have mixed feelings about `pep8speak` after seeing it in action in `astroquery`. But there is a beauty to having another bot check a bot, so 👍

**Comment by bsipocz** [comment]
I think it's still in development, and the author seemed to be happy to receive suggestions, so you can speak up :)
I always planned to get it run on astropy, but we first need to have a big cleanup so it only reports issues that are newly introduced.

**Comment by MSeifert04** [comment]
@bsipocz Are you sure that cleanup is necessary? I mean it supports [configuration](https://github.com/OrkoHunter/pep8speaks#configuration) that allow to check the "diff only" and only "specific warnings".

**Comment by MSeifert04** [comment]
Interesting, pep8speaks lists astropy in ["popular users"](https://github.com/OrkoHunter/pep8speaks#popular-users)... So we probably have to use it... 😄

**Comment by bsipocz** [comment]
@MSeifert04 - I would rather have the cleanup first, and the run it for the widest range of warnings sanely possible. The cleanup only because it will keep individual PRs cleaner of PEP8 things. I haven't tried to run it with "diff only", maybe that would be a good option for the core. But still, I would like to have it run for a wider range of warnings than the required ones in the travis tests, just to keep the code nicer.

Re: astropy as a user. From their side, they probably see the "astropy" organization as a user, as we enabled it on astroquery as a testbed. I'm very much interested in getting feedback on that experiment and if possible move forward to enable it on more repos.

**Comment by pllim** [comment]
Done.

**Comment by bsipocz** [comment]
@pllim - Oh, it seems I so badly misunderstood this, I assumed all the way that you want to use the bot to do pep8 checks on other repos...

**Comment by pllim** [comment]
Haha, no, there are already other bots for that. Just want our bot to adhere to high standards. :wink: :robot: :muscle:
